MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ScoresFunc.swift, MelodySampling/MelodySampling/TimerViewController.swift
=> Combine player and timer

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/AnswerTableViewCell.swift, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DestinationDownload.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ResultStructure.swift, MelodySampling/MelodySampling/Styleguide.swift
Play page done, starting deliever info to result
=> Play page done, starting deliever info to result

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/ResultPageViewController.swift
=> Result page layout done

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/ClearCoreDataQuestion.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/FirebaseExtension.swift, MelodySampling/MelodySampling/MelodySampling.xcdatamodeld/MelodySampling.xcdatamodel/contents, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ResultStructure.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
Clear exist question func done
=> Clear exist question func done

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/GotoFunc.swift, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/MelodySampling.xcdatamodeld/MelodySampling.xcdatamodel/contents, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/PrintUID.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/StandardTableViewCell.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
=> Landing Part Done

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/TypeChooseViewController.swift
=> genrePage fine carving done

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling.xcodeproj/xcuserdata/moon.xcuserdatad/xcschemes/MelodySampling.xcscheme, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
=> Alpha2 version.

MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
Progress animation fine carving
=> Progress animation fine carving

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/DistractorManager.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/HistoryTableViewCell.swift, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/RandomFunc.swift, MelodySampling/MelodySampling/ResultPageViewController.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
=> get distractor list func done

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DistractorManager.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift
Set stars stackView to isHidden
=> Set stars stackView to isHidden

MelodySampling/MelodySampling.xcworkspace/xcuserdata/moon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist, MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DistractorManager.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/MelodySampling.xcdatamodeld/MelodySampling.xcdatamodel/contents, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift
Distractor manager download func done.
=> Distractor manager download func done.

MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/DistractorManager.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/MelodySampling.xcdatamodeld/MelodySampling.xcdatamodel/contents, MelodySampling/MelodySampling/PlayPageViewController.swift
=> AI func done

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/ClearCoreDataQuestion.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift
Fixed bug of image not correct.
=> Fixed bug of image not correct.

MelodySampling/MelodySampling/DistractorManager.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
=> Random choose song func done.

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/HistoryTableViewCell.swift, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift
Alpha version done, layout bugs fixed.
=> Alpha version done, layout bugs fixed.

MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/zh-Hant.lproj/Main.strings
Set Landing group as Navigation controller
=> Set Landing group as Navigation controller

MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/TypeChooseViewController.swift, MelodySampling/MelodySampling/UIShadowCreator.swift
=> All corner radius done.

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/GetDeveloperToken.swift, MelodySampling/MelodySampling/MelodySampling.xcdatamodeld/MelodySampling.xcdatamodel/contents, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift, MelodySampling/MelodySampling/ResultStructure.swift
=> Firebase history

MelodySampling/MelodySampling/AppDelegate.swift, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift
Delete exist song.m4a files beofre downloading
=> Delete exist song.m4a files beofre downloading

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift
Countdown timer func done and fine tune userNameLabel.
=> Countdown timer func done and fine tune userNameLabel.

MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/zh-Hans.lproj/Localizable.strings, MelodySampling/MelodySampling/zh-Hant.lproj/Localizable.strings
Stop fetch firebase history, starting user name change func
=> Stop fetch firebase history, starting user name change func

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/GradientLayerCreater.swift, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/ResultPageViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/UpdateManager.swift, MelodySampling/MelodySampling/zh-Hans.lproj/Localizable.strings, MelodySampling/MelodySampling/zh-Hant.lproj/Localizable.strings
Fixed bugs of profile page, result page, and add change name func.
=> Fixed bugs of profile page, result page, and add change name func.

MelodySampling/MelodySampling/Base.lproj/LaunchScreen.storyboard, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/DownloadFromQuestionBank.swift, README.md
Deleted a useless func in DownloadManager
=> Deleted a useless func in DownloadManager

MelodySampling/MelodySampling.xcodeproj/project.pbxproj, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/MarqueeView.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/ja.lproj/Localizable.strings, MelodySampling/MelodySampling/zh-Hans.lproj/Localizable.strings, MelodySampling/MelodySampling/zh-Hant.lproj/Localizable.strings
新增alert controller ：
1. 登入
2. 註冊
3. 匿名登入
新增localization：繁中＆簡中
待補：日文
=> Feature/alert #100

MelodySampling/MelodySampling/Base.lproj/InfoPlist.strings, MelodySampling/MelodySampling/Base.lproj/Main.storyboard, MelodySampling/MelodySampling/LandingPageViewController.swift, MelodySampling/MelodySampling/LogInViewController.swift, MelodySampling/MelodySampling/PlayPageViewController.swift, MelodySampling/MelodySampling/ProfilePageViewController.swift, MelodySampling/MelodySampling/SignUpViewController.swift, MelodySampling/MelodySampling/en.lproj/InfoPlist.strings, MelodySampling/MelodySampling/ja.lproj/InfoPlist.strings, MelodySampling/MelodySampling/ja.lproj/Localizable.strings, MelodySampling/MelodySampling/zh-Hans.lproj/InfoPlist.strings, MelodySampling/MelodySampling/zh-Hans.lproj/Localizable.strings, MelodySampling/MelodySampling/zh-Hant.lproj/InfoPlist.strings, MelodySampling/MelodySampling/zh-Hant.lproj/Localizable.strings
修改英文流量警告
修改 ProfilePage label 更名問題
=> Storyboard 修改 userNameLabel 的寬度和 autoLayout
